### ISSUE TITLE
krnl crate looking for krnl-cache.rs in root dir resulting in no such file or directory (os error 2) on macOS

### ISSUE THREAD

**Issue by Leif-Rydenfalk** [charles-r-earp/krnl#41]
### General information
compiler:  **stable-x86_64-apple-darwin**  
os:  **macOS Sonoma 14.4.1 (23E224)**

### Errors received
user project % cargo run
   Compiling project v0.1.0 (/Users/user/project)
error: couldn't read /Users/user/project/krnl-cache.rs: No such file or directory (os error 2)
 --> src/main.rs:8:1
  |
8 | #[module]
  | ^^^^^^^^^
  |
  = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `project` (bin "project") due to 1 previous error

### With macro_backtrace flag (nightly)
user project % cargo +nightly rustc -- -Z macro-backtrace
   Compiling project v0.1.0 (/Users/user/project)
error: couldn't read /Users/user/project/krnl-cache.rs: No such file or directory (os error 2)
    --> src/main.rs:8:1
     |
8    | #[module]
     | ^^^^^^^^^ in this macro invocation
     |
    ::: /Users/user/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/macros/mod.rs:1520:5
     |
1520 |     macro_rules! include {
     |     -------------------- in this expansion of `include!`

error: could not compile `project` (bin "project") due to 1 previous error

### Reproduce this issue

Barebones project: [project.zip](https://github.com/user-attachments/files/15752687/project.zip)

**Instructions:**

1. > **Download file.**
2. > **Unzip.**
3. > **`cargo run`** or  **`cargo +nightly rustc -- -Z macro-backtrace`**

**Comment by Leif-Rydenfalk** [comment]
Make it more clear in README.md that krn-cache.rs together with krnlc is required, along with easy copy and paste instructions for installation?

**Comment by sigurd4** [comment]
> Make it more clear in README.md that krn-cache.rs together with krnlc is required, along with easy copy and paste instructions for installation?

How did you manage to install krnlc?
